/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeveloperService } from "../developer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeveloperCreateInput } from "./DeveloperCreateInput";
import { Developer } from "./Developer";
import { DeveloperFindManyArgs } from "./DeveloperFindManyArgs";
import { DeveloperWhereUniqueInput } from "./DeveloperWhereUniqueInput";
import { DeveloperUpdateInput } from "./DeveloperUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeveloperControllerBase {
  constructor(
    protected readonly service: DeveloperService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Developer })
  @nestAccessControl.UseRoles({
    resource: "Developer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDeveloper(
    @common.Body() data: DeveloperCreateInput
  ): Promise<Developer> {
    return await this.service.createDeveloper({
      data: data,
      select: {
        createdAt: true,
        email: true,
        githubProfile: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Developer] })
  @ApiNestedQuery(DeveloperFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Developer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async developers(@common.Req() request: Request): Promise<Developer[]> {
    const args = plainToClass(DeveloperFindManyArgs, request.query);
    return this.service.developers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        githubProfile: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Developer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async developer(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    const result = await this.service.developer({
      where: params,
      select: {
        createdAt: true,
        email: true,
        githubProfile: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Developer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() data: DeveloperUpdateInput
  ): Promise<Developer | null> {
    try {
      return await this.service.updateDeveloper({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          githubProfile: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Developer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    try {
      return await this.service.deleteDeveloper({
        where: params,
        select: {
          createdAt: true,
          email: true,
          githubProfile: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
