/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Repository } from "./Repository";
import { RepositoryCountArgs } from "./RepositoryCountArgs";
import { RepositoryFindManyArgs } from "./RepositoryFindManyArgs";
import { RepositoryFindUniqueArgs } from "./RepositoryFindUniqueArgs";
import { CreateRepositoryArgs } from "./CreateRepositoryArgs";
import { UpdateRepositoryArgs } from "./UpdateRepositoryArgs";
import { DeleteRepositoryArgs } from "./DeleteRepositoryArgs";
import { Project } from "../../project/base/Project";
import { RepositoryDto } from "../RepositoryDto";
import { RepositoryService } from "../repository.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Repository)
export class RepositoryResolverBase {
  constructor(
    protected readonly service: RepositoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Repository",
    action: "read",
    possession: "any",
  })
  async _repositoriesMeta(
    @graphql.Args() args: RepositoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Repository])
  @nestAccessControl.UseRoles({
    resource: "Repository",
    action: "read",
    possession: "any",
  })
  async repositories(
    @graphql.Args() args: RepositoryFindManyArgs
  ): Promise<Repository[]> {
    return this.service.repositories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Repository, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Repository",
    action: "read",
    possession: "own",
  })
  async repository(
    @graphql.Args() args: RepositoryFindUniqueArgs
  ): Promise<Repository | null> {
    const result = await this.service.repository(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Repository)
  @nestAccessControl.UseRoles({
    resource: "Repository",
    action: "create",
    possession: "any",
  })
  async createRepository(
    @graphql.Args() args: CreateRepositoryArgs
  ): Promise<Repository> {
    return await this.service.createRepository({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Repository)
  @nestAccessControl.UseRoles({
    resource: "Repository",
    action: "update",
    possession: "any",
  })
  async updateRepository(
    @graphql.Args() args: UpdateRepositoryArgs
  ): Promise<Repository | null> {
    try {
      return await this.service.updateRepository({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Repository)
  @nestAccessControl.UseRoles({
    resource: "Repository",
    action: "delete",
    possession: "any",
  })
  async deleteRepository(
    @graphql.Args() args: DeleteRepositoryArgs
  ): Promise<Repository | null> {
    try {
      return await this.service.deleteRepository(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  @nestAccessControl.UseRoles({
    resource: "Project",
    action: "read",
    possession: "any",
  })
  async getProject(
    @graphql.Parent() parent: Repository
  ): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Query(() => RepositoryDto)
  async ViewIssue(
    @graphql.Args()
    args: string
  ): Promise<RepositoryDto> {
    return this.service.ViewIssue(args);
  }
}
