/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { L2s } from "./L2s";
import { L2sCountArgs } from "./L2sCountArgs";
import { L2sFindManyArgs } from "./L2sFindManyArgs";
import { L2sFindUniqueArgs } from "./L2sFindUniqueArgs";
import { DeleteL2sArgs } from "./DeleteL2sArgs";
import { L2sService } from "../l2s.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => L2s)
export class L2sResolverBase {
  constructor(
    protected readonly service: L2sService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "L2s",
    action: "read",
    possession: "any",
  })
  async _l2sItemsMeta(
    @graphql.Args() args: L2sCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [L2s])
  @nestAccessControl.UseRoles({
    resource: "L2s",
    action: "read",
    possession: "any",
  })
  async l2sItems(@graphql.Args() args: L2sFindManyArgs): Promise<L2s[]> {
    return this.service.l2sItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => L2s, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "L2s",
    action: "read",
    possession: "own",
  })
  async l2s(@graphql.Args() args: L2sFindUniqueArgs): Promise<L2s | null> {
    const result = await this.service.l2s(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => L2s)
  @nestAccessControl.UseRoles({
    resource: "L2s",
    action: "delete",
    possession: "any",
  })
  async deleteL2s(@graphql.Args() args: DeleteL2sArgs): Promise<L2s | null> {
    try {
      return await this.service.deleteL2s(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
