/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { L2sWhereInput } from "./L2sWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { L2sOrderByInput } from "./L2sOrderByInput";

@ArgsType()
class L2sFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => L2sWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => L2sWhereInput, { nullable: true })
  @Type(() => L2sWhereInput)
  where?: L2sWhereInput;

  @ApiProperty({
    required: false,
    type: [L2sOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [L2sOrderByInput], { nullable: true })
  @Type(() => L2sOrderByInput)
  orderBy?: Array<L2sOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { L2sFindManyArgs as L2sFindManyArgs };
