/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { L2sWhereInput } from "./L2sWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class L2sListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => L2sWhereInput,
  })
  @ValidateNested()
  @Type(() => L2sWhereInput)
  @IsOptional()
  @Field(() => L2sWhereInput, {
    nullable: true,
  })
  every?: L2sWhereInput;

  @ApiProperty({
    required: false,
    type: () => L2sWhereInput,
  })
  @ValidateNested()
  @Type(() => L2sWhereInput)
  @IsOptional()
  @Field(() => L2sWhereInput, {
    nullable: true,
  })
  some?: L2sWhereInput;

  @ApiProperty({
    required: false,
    type: () => L2sWhereInput,
  })
  @ValidateNested()
  @Type(() => L2sWhereInput)
  @IsOptional()
  @Field(() => L2sWhereInput, {
    nullable: true,
  })
  none?: L2sWhereInput;
}
export { L2sListRelationFilter as L2sListRelationFilter };
