/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserStatisticService } from "../userStatistic.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserStatisticCreateInput } from "./UserStatisticCreateInput";
import { UserStatistic } from "./UserStatistic";
import { UserStatisticFindManyArgs } from "./UserStatisticFindManyArgs";
import { UserStatisticWhereUniqueInput } from "./UserStatisticWhereUniqueInput";
import { UserStatisticUpdateInput } from "./UserStatisticUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserStatisticControllerBase {
  constructor(
    protected readonly service: UserStatisticService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserStatistic })
  @nestAccessControl.UseRoles({
    resource: "UserStatistic",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserStatisticCreateInput,
  })
  async createUserStatistic(
    @common.Body() data: UserStatisticCreateInput
  ): Promise<UserStatistic> {
    return await this.service.createUserStatistic({
      data: data,
      select: {
        createdAt: true,
        id: true,
        metric: true,
        recordedAt: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserStatistic] })
  @ApiNestedQuery(UserStatisticFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserStatistic",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userStatistics(
    @common.Req() request: Request
  ): Promise<UserStatistic[]> {
    const args = plainToClass(UserStatisticFindManyArgs, request.query);
    return this.service.userStatistics({
      ...args,
      select: {
        createdAt: true,
        id: true,
        metric: true,
        recordedAt: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserStatistic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserStatistic",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userStatistic(
    @common.Param() params: UserStatisticWhereUniqueInput
  ): Promise<UserStatistic | null> {
    const result = await this.service.userStatistic({
      where: params,
      select: {
        createdAt: true,
        id: true,
        metric: true,
        recordedAt: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserStatistic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserStatistic",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: UserStatisticUpdateInput,
  })
  async updateUserStatistic(
    @common.Param() params: UserStatisticWhereUniqueInput,
    @common.Body() data: UserStatisticUpdateInput
  ): Promise<UserStatistic | null> {
    try {
      return await this.service.updateUserStatistic({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          metric: true,
          recordedAt: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserStatistic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserStatistic",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserStatistic(
    @common.Param() params: UserStatisticWhereUniqueInput
  ): Promise<UserStatistic | null> {
    try {
      return await this.service.deleteUserStatistic({
        where: params,
        select: {
          createdAt: true,
          id: true,
          metric: true,
          recordedAt: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
